name: Release
on:
  workflow_dispatch:
    inputs:
      Bumpversion:
        description: 'In above drop down slect featue branch u want to merge to master & below select which semantic version to bump'
        required: true
        default: 'warning' 
        type: choice
        options:
        - Patch
        - Minor
        - Major
      integration_test:
        description: 'Select if u want execute  integration test'
        required: true 
        type: boolean 
      backward_merge:
        description: 'Select if u want execute backward_merge'
        required: true 
        type: boolean 
      archive_branch:
        description: 'Select if u want execute Archive branch'
        required: true 
        type: boolean 
jobs:
  integration_test:
    runs-on: ubuntu-latest
    if:  ${{ inputs. integration_test }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo "The tags are hello" 
  backward_merge:
    if:  ${{ inputs.backward_merge }} 
    needs: integration_test
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: echo "The tags are hello" 
  archive_branch:
    if:  ${{ inputs.archive_branch }} 
    needs: [integration_test, backward_merge]
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: echo "The tags are hello" 
        
        
